.PHONY: clean All

All:
	@echo "----------Building project:[ Log710Shell2 - Debug ]----------"
	@cd "Log710Shell2" && "$(MAKE)" -f  "Log710Shell2.mk"
clean:
	@echo "----------Cleaning project:[ Log710Shell2 - Debug ]----------"
	@cd "Log710Shell2" && "$(MAKE)" -f  "Log710Shell2.mk" clean
