.PHONY: clean All

All:
	@echo "----------Building project:[ Log710Shell - Debug ]----------"
	@cd "Log710Shell" && "$(MAKE)" -f  "Log710Shell.mk"
clean:
	@echo "----------Cleaning project:[ Log710Shell - Debug ]----------"
	@cd "Log710Shell" && "$(MAKE)" -f  "Log710Shell.mk" clean
