.PHONY: clean All

All:
	@echo "----------Building project:[ RunCmd - Debug ]----------"
	@cd "RunCmd" && "$(MAKE)" -f  "RunCmd.mk"
clean:
	@echo "----------Cleaning project:[ RunCmd - Debug ]----------"
	@cd "RunCmd" && "$(MAKE)" -f  "RunCmd.mk" clean
