.PHONY: clean All

All:
	@echo "----------Building project:[ MemoryManager - Debug ]----------"
	@cd "MemoryManager" && "$(MAKE)" -f  "MemoryManager.mk"
clean:
	@echo "----------Cleaning project:[ MemoryManager - Debug ]----------"
	@cd "MemoryManager" && "$(MAKE)" -f  "MemoryManager.mk" clean
